name: sklearn-mlflow-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - scikit-learn==1.3.0
    - pandas==2.0.0
    - numpy==1.24.0
    - mlflow==2.9.0
    - azureml-mlflow==1.56.0
